In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
# Load the dataset
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data', header=None)


In [4]:
# Preprocess the dataset
data = data.replace('?', np.nan)
data = data.dropna()


In [5]:
# Separate the target variable from the rest of the dataset
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [6]:

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
lr = LogisticRegression()

In [8]:
lr.fit(X_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [9]:
pred = lr.predict(X_test)

In [10]:
pred

array([0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 3, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 3, 0, 0, 2, 3, 0,
       0, 0, 0, 3, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 3], dtype=int64)

In [11]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.80      0.97      0.88        36
           1       0.43      0.33      0.38         9
           2       0.25      0.20      0.22         5
           3       0.20      0.14      0.17         7
           4       0.00      0.00      0.00         3

    accuracy                           0.67        60
   macro avg       0.33      0.33      0.33        60
weighted avg       0.59      0.67      0.62        60



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
confusion_matrix(y_test,pred)

array([[35,  0,  0,  1,  0],
       [ 4,  3,  1,  1,  0],
       [ 0,  2,  1,  2,  0],
       [ 3,  2,  1,  1,  0],
       [ 2,  0,  1,  0,  0]], dtype=int64)

In [14]:
# Evaluate the performance of the model
print("Accuracy:", accuracy_score(y_test, pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, pred))
print("Classification Report:\n", classification_report(y_test, pred))

Accuracy: 0.6666666666666666
Confusion Matrix:
 [[35  0  0  1  0]
 [ 4  3  1  1  0]
 [ 0  2  1  2  0]
 [ 3  2  1  1  0]
 [ 2  0  1  0  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.97      0.88        36
           1       0.43      0.33      0.38         9
           2       0.25      0.20      0.22         5
           3       0.20      0.14      0.17         7
           4       0.00      0.00      0.00         3

    accuracy                           0.67        60
   macro avg       0.33      0.33      0.33        60
weighted avg       0.59      0.67      0.62        60



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
